"use client"

import {useContext} from "react";
import {usePathname} from "next/navigation";
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

// import Head from "next/head";

import ContextApp from "../../contexts/ContextApp";

import { ToastContainer, Slide } from "react-toastify";

import Header from "./Header/Header";
import Main from "./Main/Main";
import Footer from "./Footer/Footer";

import localFont from 'next/font/local'

const vazirmatn = localFont({
    src: '../../assets/fonts/vazirmatn/Vazirmatn-RD[wght].woff2',
    display: 'swap',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

import {Breadcrumb, CloseButton, Container} from "react-bootstrap";

import '../../app/globals.rtl.scss'
// import Icon from "../common/Icon";

export default function Layout({children}) {

    const pathname = usePathname()
    const {lang} = useContext(ContextApp)

    // -----------------------------------------------------------------------------------------------------------------

    return (
        <html lang={lang[0]} dir={lang[1]} data-bs-theme="light" data-page={pathname === '/' ? 'home' : pathname.replaceAll('/', '-').substring(1)}>
        {/*<Head>*/}
        {/*    /!*<link rel="icon" href="/favicon.ico" sizes="any" />*!/*/}
        {/*    <link rel="icon" href="/images?<generated>" type="image/<generated>" sizes="<generated>"/>*/}
        {/*</Head>*/}
        <body className={`d-flex flex-column min-vh-100 ${vazirmatn.className}`}>
            <Header/>
            <Main>
                {
                    pathname !== '/' ? (
                        <Container fluid="xxl" className="py-4 position-relative z-1">
                            <Breadcrumb id="breadcrumb" className="fs-sm fw-normal lh-1">
                                <Breadcrumb.Item href="">خانه</Breadcrumb.Item>
                                <Breadcrumb.Item href="">کالاها</Breadcrumb.Item>
                                <Breadcrumb.Item href="">لپ تاپ و نوت بوک</Breadcrumb.Item>
                                <Breadcrumb.Item active>کد فنی کالا <span className="ltr font-en">123A9096</span></Breadcrumb.Item>
                            </Breadcrumb>
                        </Container>
                    ) : (
                        <></>
                    )
                }
                {children}
            </Main>
            <Footer/>
            <ProgressBar height="2px" color="var(--bs-primary)" options={{ showSpinner: false }} shallowRouting/>
            <ToastContainer position="bottom-center" autoClose={5000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={true} pauseOnFocusLoss draggable pauseOnHover theme="dark" transition={Slide}
                            closeButton={<div className="lh-0 my-n1 me-n1 ms-3" data-bs-theme="dark"><CloseButton/></div>} />
        </body>
        </html>
    )
}